CoursesWebsite/Courses.API/Controllers/AdminUsers/CreatorController.cs
using Courses.API.Extension;
using Courses.API.Extensions.CustomAttributes;
using Courses.Infrastructure.DTO.UserDTOs;
using Courses.Infrastructure.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Courses.API.Controllers.AdminUsers
{
    [BindUser]
    [Authorize(Roles ="Admin,Creator")]
    [Layout("_Menu")]
    public class CreatorController : ApiBaseController
    {
        private readonly IAdminUserService _adminUserService;
        public CreatorController(IAdminUserService adminUserService)
        {
            _adminUserService = adminUserService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var user = await _adminUserService.GetUserDTOById(UserId);
                ViewData["Title"] = "Panel Twórcy";

                return View(user);
            }
            catch (Exception ex)
            {
                return View(new UserForAdminDTO() { UserName = "Undefined" });
            }
        }
        [HttpGet]
        public async Task<IActionResult> Courses() 
        {
            try
            {
                ViewData["Title"] = "Moje kursy";
                var courses = await _adminUserService.GetAllUserCourses(UserId);
                return View(courses);
            }catch(Exception ex)
            {
                return View();
            }
        }
        [HttpGet]
        public IActionResult Settlements()
        {
            ViewData["Title"] = "Moje rozliczenia";
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Settings()
        {
            var result = await _adminUserService.GetUserForSettings(UserId);
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> ChangeNameModal()
        {
            var result = await _adminUserService.GetUserForSettings(UserId);
            return PartialView("~/Views/Shared/Partials/Settings/_ChangeNameView.cshtml", result);
        }
        [HttpPost]
        public async Task<IActionResult> ChangeUserName([FromQuery] string userName)
        {
            try
            {
                await _adminUserService.ChangeUserName(userName,UserId);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> ChangeEmailModal()
        {
            var result = await _adminUserService.GetUserForSettings(UserId);
            return PartialView("_ChangeEmailView", result);
        }
        [HttpPost]
        public async Task<IActionResult> ChangeEmailName([FromBody] string userEmail)
        {
            try
            {
                await _adminUserService.ChangeUserEmail(userEmail,UserId);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

CoursesWebsite/Courses.API/Controllers/ShopController.cs
using Courses.Infrastructure.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Courses.API.Controllers
{
    [AllowAnonymous]
    public class ShopController : ApiBaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly ICourseService _courseService;
        private readonly ICartService _cartService;
        public ShopController(ICourseService courseService,ICategoryService categoryService,ICartService cartService):base()
        {
            _cartService = cartService;
            _categoryService = categoryService;
            _courseService = courseService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //var courses = await _courseService.GetAllAsync();
            ViewData["Title"] = "Sklep";
            return View();
        }
        public async Task<IActionResult> Catergory(Guid id)
        {
            var categoryCourses = await _categoryService.GetCoursesByCategoryIdAsync(id);
            return View(categoryCourses);
        }
        [HttpGet("Details")]
        public async Task<IActionResult> Details(Guid id)
        {
            var course = await _courseService.GetByIdAsync(id);
            return View(course);
        }
        [HttpPost("AddToCart")]
        public async Task AddToCart(Guid courseId,double price)
        {
            var cartId = Guid.Parse(HttpContext.Request.Cookies["CartId"]);
            var course = await _courseService.GetByIdAsync(courseId);
            await _cartService.AddProductAsync(courseId, course.Name,price, cartId);
        }
        [HttpPost("DeleteFromCart")]
        public async Task DeleteFromCart(Guid courseId)
        {
            var cartId = Guid.Parse(HttpContext.Request.Cookies["CartId"]);
            await _cartService.DeleteProductAsync(cartId, courseId);
        }
    }
}

CoursesWebsite/Courses.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Courses.API.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Cart.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Layout.css" asp-append-version="true" />
    <link id="Theme" rel="stylesheet" href="~/css/Themes/Theme2.css" asp-append-version="true" />

</head>
<body onload="GetTheme();" style="background-color:transparent;">
    <header >
        <div class="NaviBarMain">
            <div class="NaviBar">
                <div class="NaviDiv">
                    <a class="NaviItem" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </div>
                <div class="NaviDiv">
                    <a class="NaviItem" asp-area="" asp-controller="Shop" asp-action="Index">Sklep</a>
                </div>
                @if (!User.Identity.IsAuthenticated)
                {
                    <div class="NaviDiv">
                        <a class="NaviItem" asp-area="" asp-controller="User" asp-action="Login">Logowanie</a>
                    </div>
                }
                else
                {
                    <div class="NaviDiv">
                        <a class="NaviItem" asp-area="" asp-controller="User" asp-action="Logout">Wyloguj</a>
                    </div>
                }
                @if (this.User.IsInRole("Admin"))
                {
                    <div class="NaviDiv">
                        <a class="NaviItem" asp-area="" asp-controller="Creator" asp-action="Index">PAdmin</a>
                    </div>
                }

            </div>
            <div class="NaviCart">
                    <a id="CartBtn" onclick="OpenCart()"><img class="CartImg" src="/Images/Cart.png" /></a>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Theme.js" asp-append-version="true"></script>
    <script src="/js/OtherScript.js" asp-append-version="true"></script>
    <script src="~/js/Cart.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <footer class="bg-body-tertiary text-center text-lg-start d-grid" style="font-size:0.6rem">
        © 2024 Copyright: Grzegorz Galas.
        <b>Kontakt: <a href="mailto:grzegorzgalas10@gmail.com">Mail</a> <a href="tel:+48575442206">Telefon</a></b>
    </footer>
</body>
</html>

CoursesWebsite/Courses.API/Views/Shared/_Menu.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Cart.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/PAdminLayout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Admin.css" asp-append-version="true" />
    <link id="Theme" rel="stylesheet" href="~/css/Themes/Theme2.css" asp-append-version="true" />
    <script src="~/js/PAdmin.js" asp-append-version="true"></script>

</head>
<body onload="GetTheme(); CreateAdminPanel()">
    
        <div id="Menu" class="RightMenu">
        <div class="ResizeBtn" onclick="ResizeMenu()"></div>
        @if (User.IsInRole("Admin"))
        {
            <div class="SingleMenuItem" onclick="GoTo('Index')"><div class="MenuText"><p>Dom</p></div><div class="ImgDiv"><img src="~/Images/home.png" class="MenuImg" /></div></div>
            <div class="SingleMenuItem" onclick="GoTo('Courses')"><div class="MenuText"><p>Moje kursy</p></div><div class="ImgDiv"><img src="~/Images/courses.png" class="MenuImg" /></div></div>
            <div class="SingleMenuItem" onclick="GoTo('Settlements')"><div class="MenuText"><p>Rozliczenia</p></div><div class="ImgDiv"><img src="~/Images/settlements.png" class="MenuImg" /></div></div>
            <div class="SingleMenuItem" onclick="GoTo('Settings')"><div class="MenuText"><p>Ustawienia</p></div><div class="ImgDiv"><img src="~/Images/setting.png" class="MenuImg" /></div></div>
            <div class="SingleMenuItem" onclick="Logout()"><div class="MenuText"><p>Wyloguj</p></div><div class="ImgDiv"><img src="~/Images/logout.png" class="MenuImg" /></div></div>
        }
        else
        {
            <div class="SingleMenuItem" asp-controler="PAdmin" asp-action="Logout"><div class="MenuText"><p>Zaloguj</p></div><div class="ImgDiv"><img src="~/Images/login.png" class="MenuImg" /></div></div>
        }
        <div class="SingleMenuItem" onclick="location.href='/'"><div class="MenuText"><p>Home Page</p></div><div class="ImgDiv"><img src="~/Images/logout.png" class="MenuImg" /></div></div>
        </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Theme.js" asp-append-version="true"></script>
    <script src="/js/OtherScript.js" asp-append-version="true"></script>
    <script src="~/js/Cart.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
    <footer class="bg-body-tertiary text-center text-lg-start d-grid" style="font-size:0.6rem">
        © 2024 Copyright: Grzegorz Galas.
        <b>Kontakt: <a href="mailto:grzegorzgalas10@gmail.com">Mail</a> <a href="tel:+48575442206">Telefon</a></b>
    </footer>
</body>
</html>
<script>
    document.body.onload = function () {
        var isResize = localStorage.getItem('Resize');
        if (isResize != null) {
            if (isResize == "true") {
                var menu = document.getElementById("Menu");
                menu.style.left = 0;
                menu.classList.add("Resize");
            }
        }
    };
    function GoTo(location) {
        document.location.href = `/Creator/${location}`;
    }
    function Logout() {
        $.ajax({
            method: "POST",
            url: "/API/PAdmin/Logout",
            success: function () {
                document.location.href = `/API/PAdmin/Login`;
            },
            error: function(xhr,error){
                console.log(error);
                console.log(xhr);
            },
        })
    }
</script>